sbt:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: http://143.74.89.179
    port: 3307
    database: zxy_hospital
    username: root
    password: ntjcy@2014


  redis:
     host: localhost
     port: 6379
     password: 123456
     database: 0


