sbt:
  datasource:
    host: 106.75.7.230
    port: 2306
    database: zxy_hospital
    username: root
    password: dL0hT8iQ9n


  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0


